# Font configuration
[font.normal]
family = "Ac437_ToshibaSat_9x14 Nerd Font"


[font]
size = 36.0


[colors.primary]
background = "0x181818"
foreground = "0xb4b4b4"

[colors.cursor]
text = "0x28292d"
cursor = "0xa9a9a9"

[colors.normal]
black = "0x181818"
red = "0x96233d"
green = "0x8c933f"
yellow = "0xdd9767"
blue = "0x7a88a0"
magenta = "0x82263b"
cyan = "0x7a88a0"
white = "0x5f666e"

[colors.bright]
black = "0x373a40"
red = "0xaa314d"
green = "0x91213b"
yellow = "0x967e7f"
blue = "0x1f1f1f"
magenta = "0xaf6a87"
cyan = "0x963d52"
white = "0x9b9b9b"
