# espanso match file

# For a complete introduction, visit the official docs at: https://espanso.org/docs/

# You can use this file to define the base matches (aka snippets)
# that will be available in every application when using espanso.

# Matches are substitution rules: when you type the "trigger" string
# it gets replaced by the "replace" string.
matches:

  - trigger: ";;rn"
    replace: "site:reddit.com/r/ after:2023-01-01"
    propagate_case: false

  - trigger: ";;rb"
    replace: "site:reddit.com/r/ after:2022-01-01"
    propagate_case: false

  - trigger: ";;rs"
    replace: "site:reddit.com/r/"
    propagate_case: false

  - trigger: ";;sn"
    replace: "site:reddit.com/r/ScientificNutrition"
    propagate_case: false

  - trigger: ";;hf"
    replace: "site:head-fi.org"
    propagate_case: false

  - trigger: ";;an"
    replace: "after:2023-01-01"
    propagate_case: false

  - trigger: ";;ab"
    replace: "after:2022-01-01"
    propagate_case: false

  - trigger: ";;sw"
    replace: "SwiftUI"
    propagate_case: false

  - trigger: ";;hug2"
    replace: "https://cdn.discordapp.com/emojis/765313892783751249.gif?size=240&quality=lossless"
    propagate_case: false

  - trigger: ";;mon"
    replace: "https://streamable.com/8a6i19"
    propagate_case: false

  - trigger: ";;gasp"
    replace: "https://cdn.discordapp.com/emojis/812440825014648842.gif?size=160&quality=lossless"
    propagate_case: false

  - trigger: ";;hype"
    replace: "https://media.discordapp.net/attachments/713760162460074034/912395888779985006/FrenWiggleDance.gif "
    propagate_case: false

  - trigger: ";;gig"
    replace: "https://cdn.discordapp.com/attachments/713760162460074034/906235599231533056/giggle-emote.png "
    propagate_case: false

  - trigger: ";;think"
    replace: "https://cdn.discordapp.com/attachments/713760162460074034/901164682860183562/Thinkingfren2.png "
    propagate_case: false

  # NOTE: espanso uses YAML to define matches, so pay attention to the indentation!

  # But matches can also be dynamic:

  # Print the current date
  - trigger: ":date"
    replace: "{{mydate}}"
    vars:
      - name: mydate
        type: date
        params:
          format: "%m/%d/%Y"

  # Print the output of a shell command
  - trigger: ":shell"
    replace: "{{output}}"
    vars:
      - name: output
        type: shell
        params:
          cmd: "echo 'Hello from your shell'"

  # And much more! For more information, visit the docs: https://espanso.org/docs/
